version: '2'
services:

  test:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - TRAVIS
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
    depends_on: 
      - selenium
      - db
    ports: 
      - "9015:9015"

  db: 
    image: postgres:9.6
    ports:
      - "5432"

  selenium:
    image: selenium/standalone-firefox-debug:3.4.0
    ports:
      - "4444:4444"
      - "5900:5900"
