version: '3'

services:
  db: 
    image: postgres:9.6
    ports:
      - "5432"

  selenium:
    image: selenium/standalone-firefox-debug:3.7.1
    ports:
      - "4444:4444"
      - "5900:5900"

  test:
    image: python:3.6
    environment:
      - TRAVIS
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - DJANGO_LIVE_TEST_SERVER_ADDRESS=test
    ports:
      - 9500
    volumes:
      - .:/usr/src/app
      - pip_cache:/root/.cache/pip
      - yarn_cache:/usr/local/share/.cache/yarn/v1
    links:
      - db
      - selenium
    entrypoint:
      - /bin/sleep
      - "3600"

volumes:
  pip_cache:
  yarn_cache: