version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  test:
    image: python:3.12
    environment:
      - DJANGO_LIVE_TEST_SERVER_ADDRESS=test
    volumes:
      - .:/usr/src/app
      - pip_cache:/root/.cache/pip
      - yarn_cache:/usr/local/share/.cache/yarn/v1
    links:
      - db
    entrypoint:
      - /bin/sleep
      - "3600"

volumes:
  pip_cache:
  yarn_cache:
