version: '3'

services:
  db: 
    image: postgres:9.6
    ports:
      - "5432"

  selenium:
    image: selenium/standalone-firefox-debug:3.4.0
    ports:
      - "4444:4444"
      - "5900:5900"

  test:
    image: python:3.6
    ports:
      - 9500
    volumes:
      - .:/usr/src/app
    links:
      - db
      - selenium
    entrypoint:
      - /bin/sleep
      - "3600"
