version: '3'

services:
  db: 
    image: postgres:latest

  selenium:
    image: selenium/standalone-firefox:3.9.1-actinium

  test:
    image: python:3.6
    environment:
      - TRAVIS
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - DJANGO_LIVE_TEST_SERVER_ADDRESS=test
    volumes:
      - .:/usr/src/app
      - pip_cache:/root/.cache/pip
      - yarn_cache:/usr/local/share/.cache/yarn/v1
    links:
      - db
      - selenium
    entrypoint:
      - /bin/sleep
      - "3600"

volumes:
  pip_cache:
  yarn_cache: