# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 09:04
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations

fixture = 'initial_data'


def load_fixture(apps, schema_editor):
    # StackOverflow says it is very wrong to loaddata here, we should get
    # "old" models and then load... but, this is only a simple test app
    # so whatever. Just don't use loaddata command in your migrations or
    # don't be suprised when it stops working... without understanding why.
    call_command('loaddata', fixture, app_label='test_app')


class Migration(migrations.Migration):
    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
